name: Deploy Frontend Preview

on:
  push:
    branches:
      - "prod"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build React App
        # env:
        run: |
          cd ${{ github.workspace }}
          npm install --frozen-lockfile
          npm run build

      - name: Deploy to Nginx Server
        if: env.deploy == 'true'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/usr/share/nginx/html/veri/prod"
