name: Deploy Frontend Preview

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if commit message contains '#preview'
        id: check_commit
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"preview"* ]]; then
            echo "Commit message contains '#preview'"
            echo "deploy=true" >> $GITHUB_ENV
          else
            echo "Commit message does not contain '#preview'"
            echo "deploy=false" >> $GITHUB_ENV
          fi

      - name: Build React App
        if: env.deploy == 'true'
        # env:
        run: |
          cd ${{ github.workspace }}
          npm install --frozen-lockfile
          npm run build

      - name: Deploy to Nginx Server
        if: env.deploy == 'true'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/usr/share/nginx/html/veri"
